title: "Mulenga Bowa"
email: mulengabowa53@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Portfolio where i showcase the stuff i built as a MLH fellowship
baseurl: "/" 
url: "/portfolio-template" 
twitter_username: 
github_username:  mul53

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg